### ISSUE TITLE
Navbar position sticky or fixed top not working with design blocks

### ISSUE THREAD

**Issue by lynndesouza** [froala/design-blocks#106]
Hello, 

I'm trying to have a navbar that sticks to the top of my page, but I notice whenever I use any of the design blocks it works until it hits one of the design block elements and then they seem to stop it from sticking. I noticed that if I remove the "fdb-block" class all together then it lets the navbar keep sticking, but of course that messes up the nice structure of the blocks. Please help me out with this if you can? :)

Many thanks in advance.

**Comment by aydemiromer** [comment]
Hello
I don't know this topic yet, so sorry.
So I dont help you.


14 Ara 2018 Cum 13:42 tarihinde Lynn de Souza <notifications@github.com>
şunu yazdı:
