### ISSUE TITLE
Automate screenshot taking process

### ISSUE THREAD

**Issue by stefanneculai** [froala/design-blocks#11]
Currently, there is a [script which can be used to take screenshots](https://github.com/froala-labs/design-blocks/blob/master/screenshots/run.html), however the process is quite painful because each file should be saved manually. We're using the `dom-to-image` library to take the screenshots, but Font Awesome and Google Maps do not render correctly.

Ideally, we'd have a script which used PhantomJS or JSDom to make the screenshots without opening the browser.

**Comment by benhalverson** [comment]
@stefanneculai I've been using [siteshooter](https://github.com/devopsgroup-io/siteshooter) for work projects. It's worked well so far.

**Comment by Azael05x** [comment]
https://umaar.com/dev-tips/151-screenshot-capture/
This works well for me.

**Comment by stefanneculai** [comment]
@Azael05x thanks for the suggestion. The thing is that we would like to automate all these and have the screenshots built automatically for each block.

**Comment by zouxuoz** [comment]
@stefanneculai I think [gemini](gemini) should be good for that task, I can configure it and send PR.

**Comment by zouxuoz** [comment]
or we can use [puppeteer](https://github.com/GoogleChrome/puppeteer)

**Comment by stefanneculai** [comment]
@zouxuoz both look like good solutions. Do you have any idea if they work with iframes as well? There are some iframes loaded for Google Maps on contact forms. Some help is for sure welcome.

**Comment by zouxuoz** [comment]
@stefanneculai I think it is not problem for `puppeteer`, I can try do it and send PR on this week.
