### ISSUE TITLE
Source code of Design-Blocks builder

### ISSUE THREAD

**Issue by xclud** [froala/design-blocks#110]
Hi,
I am looking for the source code of [builder](https://www.froala.com/design-blocks/webpage-builder). But it seems i cannot find it.

I am looking to integrate the awesome builder into Microsoft's [Blazor](https://blazor.net/) and would be happy to share the code then.

**Comment by stefanneculai** [comment]
It will come as a separate product called Pages: https://www.froala.com/pages.

**Comment by guiassemany** [comment]
Hello @stefanneculai, can you tell if the builder has a release date? (Or estimated)
Thank you.
