### ISSUE TITLE
Add a detailed how to use

### ISSUE THREAD

**Issue by stefanneculai** [froala/design-blocks#16]

**Comment by wilsonkasey** [comment]
I can do this!

**Comment by stefanneculai** [comment]
@wilsonkasey please feel free to make a PR.

**Comment by wilsonkasey** [comment]
Okay, can do.

**Comment by wilsonkasey** [comment]
How do I create a pr for this?

**Comment by stefanneculai** [comment]
Please find more about that here: https://help.github.com/articles/creating-a-pull-request/.

**Comment by wilsonkasey** [comment]
So I am able to create a pull request, after speaking with someone, under my own branch. Will do. However, I am having trouble running the app on playground.
