### ISSUE TITLE
[Suggestion] PUG

### ISSUE THREAD

**Issue by peteringram0** [froala/design-blocks#17]
You should move each component into a .pug file and import / compile everything into a single .html document. That way people can install from NPM and require in the .pug components they want. This would be cleaner and upgradable with versions as you move forward.

Also side note this would satisfy the Vue community who use vue-loader

**Comment by stefanneculai** [comment]
@peteringram0 very nice suggestion. We're going to create them shortly.

**Comment by stefanneculai** [comment]
Done, we're using pug now.
