### ISSUE TITLE
How can i use it in commercial template ?

### ISSUE THREAD

**Issue by techashish12** [froala/design-blocks#19]

**Comment by stefanneculai** [comment]
We want to stimulate open web design, therefore derivative works, such as templates, are allowed to be created only under the same free license.

**Comment by jajourda** [comment]
I took a look at [issue 26](https://github.com/froala/design-blocks/issues/26) already.

**Comment by stefanneculai** [comment]
@jajourda yes, that is allowed. However, it is not allowed to create a template and sell that template.
