### ISSUE TITLE
React components

### ISSUE THREAD

**Issue by stefanneculai** [froala/design-blocks#2]
Create React components to ease the integration with React based apps.

**Comment by M-ZubairAhmed** [comment]
Hi, 
could you provide more information for me to work on this issue?

**Comment by cfey** [comment]
More information needed

**Comment by SUBHAROOP** [comment]
I want to work on this project more information needed

**Comment by ummahusla** [comment]
Nearly 2 weeks and still no reply. What a time waste. This could be added as the part of the Hactoberfest and lot's of contributors could help out with issues like this.

**Comment by stefanneculai** [comment]
We are currently discussing about moving the design blocks from HTML to Web Components / Web Elements / Polymer before creating a bridge for front-end frameworks. If you have any thoughts about that, please join the discussion: https://github.com/froala/design-blocks/issues/24.

**Comment by hetmann** [comment]
@stefanneculai if you're interested, I can personally add a new branch to my open-source project @react-ui-kit to create ReactJS components/elements using @froala design-blocks styling.

**Comment by aaosuarez** [comment]
@stefanneculai Is there any update on this issue? Would love to contribute!

**Comment by sajadghawami** [comment]
would love to contribute too! :)

**Comment by karanrajpal14** [comment]
@stefanneculai any update on this? Would love to see this happen and possibly contribute as well.

**Comment by pblanton** [comment]
+1 for someone who would like to pitch in and help with this.

**Comment by stefanneculai** [comment]
Here it comes: https://github.com/froala/react-froala-design-blocks. ✨✨✨

**Comment by karanrajpal14** [comment]
Thank you @stefanneculai
