### ISSUE TITLE
Relative path issue on my Mac

### ISSUE THREAD

**Issue by pascalandy** [froala/design-blocks#30]
Hello folks,
I download the zip. From /dist I tried the HTML files. Everything was broken.

I went in the code and I saw:
`<link type="text/css" rel="stylesheet" href="../css/froala_blocks.css">`

I changed it to:
`<link type="text/css" rel="stylesheet" href="./css/froala_blocks.css">`

and it worked. I did the same thing for the img paths.

It's the first time I tried a bootstrap library that brakes like this.

What should be the standard? `../css/froala_blocks.css">` or `./css/froala_blocks.css">`

Cheers!

**Comment by Gianlucca** [comment]
Am having the same issue on Windows.

**Comment by Gianlucca** [comment]
#40

**Comment by stefanneculai** [comment]
It's fixed now.
