### ISSUE TITLE
minify version

### ISSUE THREAD

**Issue by pascalandy** [froala/design-blocks#31]
Hi,
In the readme, we can see:

```
design-blocks/
├── dist/
│   ├── css/
│   │   ├── froala_blocks.css
│   │   └── froala_blocks.min.css
```

But in the zip file, I downloaded `froala_blocks.min.css` is not there. I don't mind creating the min.css myself but the readme is not representing the tree. 

Cheers!

**Comment by stefanneculai** [comment]
@pascalandy it's coming shortly. :)

**Comment by tristix** [comment]
Im not seeing the dist dir at all in the zip file atm

**Comment by stefanneculai** [comment]
@tristix that's because you downloaded from the dev branch, not the master one: https://github.com/froala/design-blocks/tree/master.

**Comment by tristix** [comment]
Thanks @stefanneculai !
