### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by alejandro01970** [froala/design-blocks#33]
Hello all, I am new to Github and this is my first time installing a software using it. I followed ll the steps and I dont see to get it to install on my mac. I run the install on Terminal and I get this: 

npm WARN enoent ENOENT: no such file or directory, open '/Users/PixarMediaMac/package.json'
npm WARN PixarMediaMac No description
npm WARN PixarMediaMac No repository field.
npm WARN PixarMediaMac No README data
npm WARN PixarMediaMac No license field.

I see a "Node_modules" folder on my mac but that does not open a software.

Thank you all.

**Comment by stefanneculai** [comment]
Hi @alejandro01970! After cloning the repo, please make sure you move into that directory `cd design-blocks` and just after that do the npm stuff.

**Comment by alejandro01970** [comment]
Thank you @stefanneculai I did that before and I just did it now and I still got the same error:

npm WARN enoent ENOENT: no such file or directory, open '/Users/PixarMediaMac/package.json'
npm WARN PixarMediaMac No description
npm WARN PixarMediaMac No repository field.
npm WARN PixarMediaMac No README data
npm WARN PixarMediaMac No license field.

thank you,

**Comment by stefanneculai** [comment]
It looks like you are not in the correct folder. Please do the following in this order:

```bash
git clone git@github.com:froala/design-blocks.git
cd design-blocks

npm install
npm install -g gulp
gulp
```

**Comment by alejandro01970** [comment]
Thank you stefanneculai, should I type that into Terminal?

**Comment by stefanneculai** [comment]
yep.

**Comment by dianaprajescu** [comment]
@alejandro01970 it seems that cloning the repo failed because GitHub couldn't authenticate you. Here's how you can fix this: https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey
