### ISSUE TITLE
Make Froala available to the "rest of the world"

### ISSUE THREAD

**Issue by lwoods** [froala/design-blocks#37]
I do development and use a public hosting company---as do the majority of developers.  I don't have---and don't know how to use "npm".  Would you consider making a simple zip of Froala that can be used by us "unwashed?"

Thanks for your consideration

**Comment by robinator8** [comment]
If you look under quick start in the readme, there is a zip of the latest release that you can use. From the dist folder you can open those html files and take out any section for use in projects.

**Comment by lwoods** [comment]
Thanks for the quick reply.  And apologies for not being "up" on the latest.  I will dig in.
