### ISSUE TITLE
Integration with bootstrap by using their variables

### ISSUE THREAD

**Issue by Remo** [froala/design-blocks#38]
I've had a look at this project for a bit and it looks really great, but one thing I don't quite understand.

While everything is built on top of bootstrap, it doesn't look like it's integrated into bootstrap.

If I use a bootstrap plugin that uses default buttons like `btn-primary` and `btn-warning` I'll have a different style on those buttons. Why not import the bootstrap scss and use their variables?

What's your idea about using the design blocks with other bootstrap components to achieve a consistent look'n'feel?

**Comment by stefanneculai** [comment]
Good idea!

**Comment by stefanneculai** [comment]
Done.
