### ISSUE TITLE
Not displaying properly?

### ISSUE THREAD

**Issue by alphadesigns** [froala/design-blocks#41]
So I downloaded the _latest_ release, and when I open any **.html** file from the **dist** folder it displays like this - is it normal? Seems like it isn't:

![screenshot_1](https://user-images.githubusercontent.com/26995439/31877195-4b1d241a-b821-11e7-93da-79014702e9f5.png)

![screenshot_2](https://user-images.githubusercontent.com/26995439/31877387-04df8f78-b822-11e7-8f0c-1109184c0069.png)

I use Google Chrome.

**Comment by stefanneculai** [comment]
@alphadesigns it's fixed now.
