### ISSUE TITLE
Large view of the design block screenshots on homepage

### ISSUE THREAD

**Issue by Sanjo** [froala/design-blocks#58]
In the playground section on the [Design Blocks homepage](https://www.froala.com/design-blocks) when you click on a design block screenshot, a larger version of the screenshot should be shown so I can see the design block more detailed. Right now the cursor changes to a pointer but when I click on a screenshot, nothing happens.

**Comment by stefanneculai** [comment]
In the meanwhile, we have a Builder for it: https://www.froala.com/design-blocks/webpage-builder.

**Comment by stefanneculai** [comment]
Done.
