### ISSUE TITLE
New Blocks Request & Possibility for creating own Blocks

### ISSUE THREAD

**Issue by manwithsteelnerves** [froala/design-blocks#60]
Blocks such as Tabs + Accordions are much helpful for creating documentation. Can we see it added anytime soon?

And also is it possible to create our own blocks? If so can you please point to documentation?

**Comment by dianaprajescu** [comment]
We're going to add a guide for creating new design blocks soon. I'll keep you posted.

**Comment by dianaprajescu** [comment]
Here is the wiki page with guides for creating [new design blocks](https://github.com/froala/design-blocks/wiki/How-to-create-New-Design-Blocks). Let us know if you have any questions or suggestions regarding it.

We would be very thankful if you could share with us the design blocks created by you.

I'm going to close this issue in favor of #1

**Comment by manwithsteelnerves** [comment]
Sure! Thanks for sharing!
