### ISSUE TITLE
Build when installed with npm

### ISSUE THREAD

**Issue by schwiet** [froala/design-blocks#69]
In the quickstart, it says one of the options is to:

>Install with npm: `npm install froala-design-blocks`

But it is not obvious how to then use it to build your project.

Overall, the documentation seems lacking; when trying it out with a fresh clone, the best I could figure to do was copy-paste from the various block files into the index.html file. Is that the intended use?

**Comment by dianaprajescu** [comment]
The project contains HTML and CSS design blocks. A fresh clone of the repo will allow you to browse the existing blocks and spot the ones you like and want to use. Then what you have to do is indeed copy-paste the code for them in your own application.

We're planning to create an easier way to browse, combine the blocks in a simple interface, and then just download the source code directly. All of these without browsing through different files and copy pasting code. We'll post on social media about that when it's ready.
