### ISSUE TITLE
Button type="submit"

### ISSUE THREAD

**Issue by alexandre-pereira** [froala/design-blocks#73]
Hello,

Tested on Chrome, on the button elements with type="submit" and not type="button", it's missing:

cursor:pointer

Cheers

**Comment by m5o** [comment]
hey @alexandre-pereira 

It's because design-blocks are currently based on bootstrap alpha
https://v4-alpha.getbootstrap.com/components/buttons/#examples

It will be fixed with bootstrap final v4, see: https://getbootstrap.com/docs/4.1/components/buttons/#examples

🔗 #72

**Comment by stefanneculai** [comment]
It's fixed now.
