### ISSUE TITLE
Understanding Froala design blocks

### ISSUE THREAD

**Issue by angusgrant** [froala/design-blocks#79]
Hi I guess I might be the only person in the world who is slightly confused by froala design-blocks are they designed specifically to be used with the Froala WYSIWYG editor or not??

I am working on a CMS product. Which already provides the function to create new (blank) pages to an existing site.  Each new page is currently editable through a single Froala WYSIWYG interface. However I have a requirement to provide a choice of different editable templates that are then editable through a single Froala WYSIWYG interface. Is this feasible?

Is this something that they are designed to do? If not is there purpose to just generate static template/layouts and how would they best be integrated with the Froala editor so all the text etc can be  edited and new html blocks added by individual users?

Do we have some example (fiddles/codepens) of how they are best used by the editor because I cant see any examples on your site?

Thanks for your time.

Angus (Froala customer)

**Comment by stefanneculai** [comment]
The Froala Design blocks were created with the main scope of helping devs to easily put together a design for the apps they built. They were not designed to be integrated with the Froala Editor in any way out-of-the-box. Indeed, there were few requests for such an integration and that is the main reason why we're putting together the Froala Pages (https://www.froala.com/pages) which would be available shortly as away of editing the design blocks and combining them together easily.
